language: rust
rust:
  - nightly

os: linux
dist: bionic

addons:
  apt:
    packages:
      - build-essential
      - binutils-dev
      - libcurl4-openssl-dev
      - libdw-dev
      - libiberty-dev
      - zlib1g-dev

env:
  global:
    - MODE_X=DEBUG
    - KCOV=1

jobs:
  include:
    - env: TARGET_X=aarch64-unknown-linux-gnu
      arch: arm64
    - env: TARGET_X=x86_64-unknown-linux-gnu
      arch: amd64

script: mk/travis.sh
