language: rust
rust:
  - nightly

cache:
  directories:
    - $HOME/kcov

os: linux
dist: bionic

arch: arm64

env:
  - TARGET_X=aarch64-unknown-linux-gnu CC_X=gcc MODE_X=DEBUG KCOV=1


script: mk/travis.sh
