language: rust
cache:
  directories:
    - $HOME/kcov
matrix:
  include:
    - env: TARGET_X=x86_64-unknown-linux-gnu CC_X=gcc-7 FEATURES_X= MODE_X=DEBUG KCOV=1 RUST_X=nightly
      rust: nightly
      os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - binutils-dev
            - g++-7
            - gcc-7
            - libcurl4-openssl-dev
            - libdw-dev
            - libelf-dev
            - libiberty-dev
          sources:
            - ubuntu-toolchain-r-test

    - env: TARGET_X=i686-unknown-linux-gnu CC_X=gcc-7 FEATURES_X= MODE_X=DEBUG KCOV=1 RUST_X=nightly
      rust: nightly
      os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - g++-7
            - g++-7-multilib
            - gcc-7
            - gcc-7-multilib
            - libcurl3:i386
            - libcurl4-openssl-dev:i386
            - libdw-dev:i386
            - libelf-dev:i386
            - libiberty-dev:i386
            - libkrb5-dev:i386
            - libssl-dev:i386
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test

script: mk/travis.sh
