language: rust
rust:
  - nightly

cache:
  directories:
    - $HOME/kcov

os: linux
dist: bionic

arch: arm64

addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - libdw-dev
      - libelf-dev
      - libiberty-dev
env:
  - TARGET_X=aarch64-unknown-linux-gnu CC_X=gcc MODE_X=DEBUG KCOV=1

script: mk/travis.sh
