language: rust
rust:
  - stable
  - beta
  - nightly
arch: arm64
os: linux
dist: trusty

env:
  - TARGET_X=aarch64-unknown-linux-gnu CC_X=gcc FEATURES_X= MODE_X=DEBUG KCOV=0 RUST_X=stable
  - TARGET_X=aarch64-unknown-linux-gnu CC_X=gcc FEATURES_X= MODE_X=RELWITHDEBINFO KCOV=0 RUST_X=stable

script: if [[ "$TARGET_X" =~ ^a*.*linux-.* && "$MODE_X" == "RELWITHDEBINFO" ]]; then travis_wait 60 mk/travis.sh; else mk/travis.sh; fi
